/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_dkp;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTugas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUas = new javax.swing.JTextField();
        txtUts = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        outNama = new javax.swing.JTextField();
        outNim = new javax.swing.JTextField();
        outRata = new javax.swing.JTextField();
        outGrade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outKet = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Perhitungan Akumulasi Nilai Mahasiswa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 570, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NIM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 210, 30));

        txtNama.setAutoscrolls(false);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, 40));
        getContentPane().add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 210, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nilai Tugas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 120, 30));
        getContentPane().add(txtTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 120, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nilai UAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 110, 30));
        getContentPane().add(txtUas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 110, 40));
        getContentPane().add(txtUts, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 110, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nilai UTS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 110, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 90, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("NIM");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 90, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Rata-rata");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 90, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Index");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 90, 30));

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 100, 40));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 110, 40));

        outNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outNamaActionPerformed(evt);
            }
        });
        getContentPane().add(outNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 150, 30));

        outNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outNimActionPerformed(evt);
            }
        });
        getContentPane().add(outNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 150, 30));
        getContentPane().add(outRata, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 150, 30));
        getContentPane().add(outGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 150, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Keterangan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 110, 20));

        outKet.setColumns(20);
        outKet.setRows(5);
        outKet.setBorder(null);
        jScrollPane1.setViewportView(outKet);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 230, 120));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\Lightshot\\2.png")); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void outNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outNimActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
        txtNim.setText("");
        txtTugas.setText("");
        txtUts.setText("");
        txtUas.setText("");
        outNama.setText("");
        outNim.setText("");
        outRata.setText("");
        outGrade.setText("");
        outKet.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        String nama = txtNama.getText();
            String nim = txtNim.getText();
        if (txtNama.getText().isEmpty() || txtNim.getText().isEmpty() || txtTugas.getText().isEmpty() || txtUts.getText().isEmpty() || txtUas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Harus Diisi");
        }
        else {
            Double tugas, uts, uas, rata;
                tugas = Double.parseDouble(txtTugas.getText());
                uts = Double.parseDouble(txtUts.getText());
                uas = Double.parseDouble(txtUas.getText());
                rata = (tugas + uts + uas)/3;
            outRata.setText(rata.toString().substring(0,5));
            outNama.setText(nama);
            outNim.setText(nim);
        }
        
        Double i = Double.parseDouble(outRata.getText());
        char index=' ';
        if (i >= 90) {
            index = 'A';
            outGrade.setText("" +index);
        }
        else if (i <= 89 && i >= 75) {
            index = 'B';
            outGrade.setText("" +index);
        }
        else if (i <= 74 && i >= 60) {
            index = 'C';
            outGrade.setText("" +index);
        }
        else if (i <= 59) {
            index = 'D';
            outGrade.setText("" +index);
        }
        
        if (index == 'A' || index == 'B' || index == 'C') {
            outKet.setText("Mahasiswa bernama " +nama+ "\ndengan NIM " +nim+ "\nmendapatkan index " +index);
        }
        else {
            outKet.setText("Maaf " +nama+ "\nanda mendapatkan index " +index+ "\ndan anda harus mengulang");
        }
        
        
    }//GEN-LAST:event_btnHitungActionPerformed

    private void outNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField outGrade;
    private javax.swing.JTextArea outKet;
    private javax.swing.JTextField outNama;
    private javax.swing.JTextField outNim;
    private javax.swing.JTextField outRata;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUas;
    private javax.swing.JTextField txtUts;
    // End of variables declaration//GEN-END:variables
}
